import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage();
await p.setViewportSize({ width: 1400, height: 900 });
await p.goto("http://localhost:3000/lab?from=SEO&to=LCC&race=1", { waitUntil: "networkidle" });
await p.waitForTimeout(900);
await p.getByRole("button", { name: "Race", exact: true }).first().click();
await p.waitForSelector(".panel-map", { timeout: 20000 });
await p.waitForTimeout(6000);
await p.screenshot({ path: "scripts/shots/race-zoom.png" });
console.log("saved");
await b.close();
